import type {NextPage} from 'next';
import Head from 'next/head';
import {Fragment} from 'react';
import Homepage from "../components/Home"

const Home: NextPage = () => {
  return (
    <Fragment>
      <Head>
        <title>Bowell</title>
        <meta name="description" content="Generated by create next app"/>
        <link rel="icon" href="/favicon.ico"/>
      </Head>

      <Homepage/>
    </Fragment>
  );
};

export default Home;
