name: Frontend workflow
on:
  push:
    branches:
      - '*'

  pull_request:
    branches:
      - main

jobs:
  jest-tests:
    name: Jest run
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Install dependencies
        run: |
          yarn install
      - name: Run tests
        run: |
          yarn test --coverage

  cypress-tests:
    name: Cypress run
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          build: yarn build
          start: yarn start
          wait-on: http://localhost:3000
  
  build-image:
    needs: [jest-tests, cypress-tests]
    runs-on: ubuntu-latest
    name: Build docker image and push
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to private container registry
      uses: docker/login-action@v1 
      with:
        registry: ${{ secrets.PCR_URL }}
        username: ${{ secrets.PCR_USER_NAME }}
        password: ${{ secrets.PCR_PASSWORD }}
    - name: install buildx
      id: buildx
      uses: crazy-max/ghaction-docker-buildx@v1
      with:
        version: latest
    - name: build the image
      run: |
        docker buildx build \
          --tag ${{ secrets.PCR_URL }}/bowelsound/frontend:${{ github.run_id }}_${{ github.run_number }} \
          --tag ${{ secrets.PCR_URL }}/bowelsound/frontend:latest
          --platform linux/amd64,linux/arm/v7,linux/arm64 --push=true .
